/* Clear tables for insertion */
DELETE FROM types;
DELETE FROM events;
DELETE FROM personalities;
DELETE FROM holdings;
DELETE FROM followers;
DELETE FROM attachments;
DELETE FROM monk_shugenja_attachments;
DELETE FROM strongholds;
DELETE FROM winds;
DELETE FROM senseis;
DELETE FROM rings;
DELETE FROM acts;
DELETE FROM regions;


/* Insert into Types table */
INSERT INTO types VALUES ('0', 'Neither');
INSERT INTO types VALUES ('1', 'Dynasty');
INSERT INTO types VALUES ('2', 'Fate');

/* Insert into Event table */
INSERT INTO events VALUES ('Cross-Clan Wedding', '1', 'Choose a Personality you control and another player.  The player takes control of the Personality.  If he now controls the Personality, he chooses another Personality he contolrs\;take control of him.');
INSERT INTO events VALUES ('Emperor\'s Peace', '1', 'No attacks can be made by any player until after the beginning of your next turn.');
INSERT INTO events VALUES ('Glimpse of the Unicorn', '1', 'Dynasty: Draw a card. (You may only take Dyasty actions during your Dynasty Phase.)');
INSERT INTO events VALUES ('Honorable Sacrifice', '1', 'Target one of your Samurai.  The Samurai commits Seppuku and is destroyed.  Until after your Straighten Phase three turns from now, any player bringing into play a Human Personality with Personal Honor less than the Samurai\'s must either bow one of his or her Personalities or pay 3 extra Gold for the Personality.');
INSERT INTO events VALUES ('Iris Festival', '1', 'All Shadowlands cards in play are destroyed.');
INSERT INTO events VALUES ('Kachiko\'s Promises', '1', 'Until the beginning of your next turn, other players must discard a card from their hands as an additional cost of playing a card that targets you or any of your cards.');
INSERT INTO events VALUES ('Kolat Courtiers', '1', 'Gain the Imperial Favor.  Lose 4 Honor, a loss you cannot prevent using the Imperial Favor.');
INSERT INTO events VALUES ('Mine Cave-in', '1', 'Bow a Mine.  The Mine does not straighten during its owner\'s next Straighten Phase.  You may shuffle this Event back into your Dynasty deck.  This Event resolves every time it appears in a Province.  This effect cannot target any Mine more than once per game.');
INSERT INTO events VALUES ('Return of the True Champion', '1', 'Until after your Events Phase two turns from now, players cannot bring Imperial cards into play.');
INSERT INTO events VALUES ('Selection of the Chancellor', '1', 'All Personalities are candidates for Chancellor.  Any Personality may vote for any Personality (including themselves) by bowing as a Political Limited action, giving votes to the candidate equal to their Personal Honor.  At the beginning of your next events phase, the Personality with the most votes becomes the Chancellor.  The Chancellor\'s controller gains 5 honor and the Imperial Favor.');
INSERT INTO events VALUES ('Courtly Sabotage', '1', 'This card remains in play in your home.\nOpen: Discard this cardand bow your Stronghold.  Until the end of the turn, that player\'s Stronghold to target a player.  Bow his Stronghold.  Until the end of the turn, that player\'s Stronghold and Wind produce no effects except those involving victory or elimination conditions or changes to his Family Honor.');
INSERT INTO events VALUES ('Imperial Ambassadorship', '1', 'In turn order, each other player may draw a card.  You may look at the top three cards of your Fate deck and put them back in any order. Then, draw a card.');
INSERT INTO events VALUES ('In Time of War', '1', 'Until the end of the game, during each turn, a player\'s Family Honor can not rise over its value when that turn began plus 5.');
INSERT INTO events VALUES ('My Enemy\'s Weakness', '1', 'Until the beginning of your next turn, any player who destroys a Province as the Attacker may pay 5 Gold immediately to gain an additional Province to the right of his rightmost Province.  Each player may do this once during this time.');
INSERT INTO events VALUES ('New Year\'s Celebation', '1', 'Each player discards his hand, then draws five cards.');
INSERT INTO events VALUES ('Shadow of the Dark God', '1', 'Permanently lower the strength of each Province by 1.');
INSERT INTO events VALUES ('Restoring the Doji Treasury', '1', 'Each player may search his Dynasty deck for one Gold-producing Holding, lower its Gold cost by 3, and put it into play bowed, paying all remaining costs.');
INSERT INTO events VALUES ('Norikazu\'s Ravings', '1', 'Until the end of the game, destroy each Spell after it is cast.');
INSERT INTO events VALUES ('Wisdom Gained', '1', 'Open: Starting with you, each player may search his discard pile and Fate deck for a Ring, show it, and put it in his hand.');

/* Insert into Personality table */
INSERT INTO personalities VALUES ('Yotsu Seiki', '1', '1', '2', '4', null, '1', 'Unaligned Shugenja, Battle', 'Battle: Bow for Ranged Attack equal to her Chi.', 'Unaligned');
INSERT INTO personalities VALUES ('Bayushi Dairu', '1', '3', '2', '7', null, '2', 'Scorpion Clan Samurai, Unique, Battle', 'Battle: Bow Dairu to give a -1C venom token to any opposing Personality.  While that Personality has any venom tokens, any time he performs an action, he gains an additional -1C venom token.  Whenever the target has an opportunity to straighten, he may destroy one venom token if he is already unbowed.  Lose 2 Honor.', 'Scorpion');
INSERT INTO personalities VALUES ('Hida Matyu', '1', '1', '2', '4', '0', '2', 'Crab Clan Cartographer, Limited', 'Limited: Bow Matyu and discard a terrain card from your hand.  Go through your Fate deck and select any one terrain card.  Reveal the terrain card to your opponents and put it in your hand.  Shuffle your Fate deck.', 'Crab');
INSERT INTO personalities VALUES ('Shazaar', '1', '2', '2', '6', '0', '2', 'Naga Scout, Open, Battle', 'Open: Bow any of your Pearl Beds or Pearl Divers to place a pearl token on Shazaar.\nBattle: Bow and destroy any numbers of pearl tokens on Shazaar to produce a Ranged Attack targeting a Shadowlands card.  This Ranged Attack has a strength equal to twice the number of pearl tokens destroyed.', 'Naga');
INSERT INTO personalities VALUES ('Shinja Goshi', '1', '3', '3', '7', '0', '3', 'Unicorn Clan Samurai, Cavalry', 'This Personality may have a Follower attached as he is being put into play.  All costs must be paid normally.', 'Unicorn');
INSERT INTO personalities VALUES ('Kitsu Dejiko', '1', '4', '4', '9', '8', '3', 'Lion Clan Samurai, Reaction', 'Reaction: Once per turn, when another player takes an action during a battle containing Dejiko in which the player has no Personalities, bow Dejiko to cancel the action.', 'Lion');
INSERT INTO personalities VALUES ('Yoritomo Kitao', '1', '2', '2', '6', '2', '1', 'Mantis Clan of the Bitter Flower, Samurai', null, 'Mantis');
INSERT INTO personalities VALUES ('Asako Misao', '1', '1', '3', '5', '1', '2', 'Phoenix Clan Shugenja, Limited', 'Limited: Bow Misao and one of your Personalities with the Ninja, Shadowlands, or Bloodspeaker trair to permanently remove the Ninja, Shadowlands, or Bloodspeaker trait from the Personality', 'Phoenix');
INSERT INTO personalities VALUES ('Shiba Tsukune', '1', '3', '2', '5', '5', '2', 'Phoenix Clan Samurai, Reaction', 'Reaction: When Tsukune enters a duel with a Shugenja, she gains +3C.', 'Phoenix');
INSERT INTO personalities VALUES ('Fushiki no oni', '1', '5', '4', '8', null, '0', 'Fire, Nonhuman, Oni, Shadowlands, Fire Battle', 'After Fushiki enters play, lose 4 Honor.\nFire Battle: Destroy a target Fortification at this battlefield with Gold Cost lower than Fushiki\'s Force.  Give Fushiki a +1F token', 'Shadowland');
INSERT INTO personalities VALUES ('Mirumoto Kaiji', '1', '4', '5', '9', '5', '3', 'Dragon Clan Hero, Samurai, Singular', 'If your Stronghold is Shiro Mirumoto, your Personalities in this battle may perform Limited Action cards that issue challenges as if they were Battle actions.  The challenged Personality must be opposing the challenger.\nKaiji may perform Shiro Mirumoto\'s printed ability wihtout bowing.', 'Dragon');
INSERT INTO personalities VALUES ('Hitomi Mae', '1', '3', '2', '7', '0', '2', 'Dragon Clan Monk, Acolyte of Fire, Soul of Takao, Elemental, Reaction', 'Elemental Reaction: When ae enters a duel against an opponent with higher Chi, Mae has the first opportunity to focus or stike.\nElemental Reaction: When Mae enters a duel while you have a Ring of Fire in play, destroy one Weapon attached to her opponent.', 'Dragon');
INSERT INTO personalities VALUES ('Daidoji Akagi', '1', '1', '3', '5', '0', '2', 'Crane Clan, Samurai, Scout, Battle, Reaction', 'Battle: Bow Akagi: Ranged 2 Attack.\nReaction: After you target a Ranged Attack from an action that Akagi performed, even it he is bowed, discard a card: increase the Ranged Attack\'s strength by the card\'s Focus Value.', 'Crane');
INSERT INTO personalities VALUES ('Daidoji Ryunosuke', '1', '2', '3', '6', null, '2', 'Crane Clan Samurai, Harrier, Battle', 'Ranged Attacks may not target Ryunosuke\'s Followers.\nBattle: Once per battle, if you control a Terrain: Target an opposing Personality.  Give him -3F.\nBattle: Once per battle, if another player controls a Terrain: Target up to 2 Personalities that player controls at Ryunosuke\'s battlefield.  Bow them.', 'Crane');
INSERT INTO personalities VALUES ('Ruantek', '1', '1', '3', '6', null, '1', 'Ratling Scout, Grasping Paw Tribe, Creature, Cavalry', 'Ratling Followers gain the Cavalry trait while attached to Ruantek.', 'Ratling');
INSERT INTO personalities VALUES ('Bayushi Muhito', '1', '3', '4', '7', null, '1', 'Scorpion Clan, Samurai, Ninja, Reaction', 'Reaction: After an action resolves that moved Muhito to or from a battlefield: Take an additional Battle action.', 'Scorpion');
INSERT INTO personalities VALUES ('Moto Gurban', '1', '3', '3', '8', null, '2', 'Unicorn Clan Bushi, Cavalry, Reaction', 'Gurban gains +1F if she has an item.\nReaction: Once per turn, when a Limited action targets one of your Personalities, cancel it.  Permanently reduce Gurban\'s Personal Honor by the number of other Personalities you control.  If her new Personal Honor is 0, Gurban commits seppuku.', 'Unicorn');
INSERT INTO personalities VALUES ('Daigotsu Masami', '1', '3', '2', '7', null, '0', 'Spider Clan, Samurai, Shadowlands, Limited', 'Lose 4 Honor.  After the first time each turn Masami leaves play, he permanently gains +1F.\nLimited: If Masami is dead: Discard a card in one of your Provinces, refilling it face up with Masami.', 'Spider');
INSERT INTO personalities VALUES ('Asako Meisuru', '1', '3', '4', '7', '0', '3', 'Phoenix Clan, Water, Shugenja, Battle', 'Battle: Target one or more cards in Meisuru\'s army up to her Chi: Straighten them.', 'Phoenix');
INSERT INTO personalities VALUES ('Matsu Bunka', '1', '2', '2', '5', '3', '3', 'Lion Clan, Samurai, Reaction', 'Reaction: Before resolution of a battle Bunka is in, if you are the Attacker and Buna is opposed: Gain 3 Honor.', 'Lion');

/* Insert into Holding table */
INSERT INTO holdings VALUES ('Ashalan Sandsmith', '1', '4', '2', null, 'Limited, Battle', 'Bow the Ashalan Sandsmith to produce 2 Gold.\nLimited: Bow the Ashalan Sandsmith to place a +1C Crystal Weapon Item on a Personality.\nBattle: If one or more Ninja Personalities or Shadowlands Personalities are in the opposing army, bow the Ashalan Sandsmith to give a +2F/+2C bonus to each Crystal Weapon token in this battle until the turn ends.');
INSERT INTO holdings VALUES ('Barracks', '1', '2', null, null, 'Fortification', 'You may attach Followers to the Barracks, ignoring Honor requirements, for half of their Gold cost, rounded down after modifications.  The Followers cannot detach.  During battles at this Province, if the Barracks and its Followers act as a defending unit if the Barracks and has any Followers attached.  The unit has no Personality and cannot leave battle.');
INSERT INTO holdings VALUES ('Basecamp', '1', '3', '2', null, null, 'Bow the Basecamp to produce 2 Gold.\nIf a Toturi\'s Army player controls the Basecamp, you can bow it to produce 4 Gold when bringing a Follower, an Unaligned Samurai, or a Toturi\'s Army Personality into play.');
INSERT INTO holdings VALUES ('Black Market', '1', '2', '2', null, null, 'Lose 3 Honor.  All trade Routes  in play produce 2 less Gold.  All Ports in play produce 1 less Gold.\nBow the Black Market and lose 1 Honor to produce 2 Gold.  If a Crane player controls the Black Market, it produces 3 Gold when bowed.');
INSERT INTO holdings VALUES ('Bushi Dojo', '1', '3', '6', null, null, 'Bow the Bushi Dojo to produce 6 Gold when paying for a Follower or an action that creates a Follower token.');
INSERT INTO holdings VALUES ('Corrupted Dojo', '1', '3', '4', null, null, 'Bow the Corrupted Dojo to produce 4 Gold when paying for a Human Shugenja.  The Shugenja permanently has -1C and gains the Shadowlands trait.');
INSERT INTO holdings VALUES ('Empty Crevasse', '1', '2', '3', null, 'Fortification, Iron Mine', 'The Empty Crevasse enters play bowed.  Bow the Empty Crevasse to produce 3 Gold.');
INSERT INTO holdings VALUES ('Fantastic Gardens', '1', '7', null, '2', 'Limited', 'Fantastic Gardens costs 2 less Gold for Crane Clan players.\nLimited: Bow Fantastic Gardens to gain 2 Honor.');
INSERT INTO holdings VALUES ('Forest', '1', '1', '1', null, null, 'Bow the Forest to produce 1 Gold\nBow the Forest to produce 2 Gold when paying for a Personality with the Creature or Nonhumna trait or a Follower with the Creature or Nonhuman trait.');
INSERT INTO holdings VALUES ('Gambling House', '1', '3', '0', null, null, 'When you bring the Gambling House into play, discard your Fate deck\'s top card.  The card\'s Focus Value is the Gambling House\'s printed Gold production for the rest of the game.');
INSERT INTO holdings VALUES ('Go Master', '1', '3', null, null, 'Retainer, Battle', 'Battle: Bow the Go Master to play a Terrain, which destroys any Terrain in play.');
INSERT INTO holdings VALUES ('Hawks and Falcons', '1', '3', null, '1', 'Limited', 'Limited: Bow Hawks and Falcons togain 1 Honor.');
INSERT INTO holdings VALUES ('The Hiruma Dojo', '1', '4', '3', null, 'Reaction', 'Bow the Hiruma Dojo to produce 3 Gold.\nReaction: When paying for a Samurai, bow the Hiruma Dojo to lower that Samurai\'s Gold cost by 4.');
INSERT INTO holdings VALUES ('Iron Mine', '1', '2', '2', null, null, 'Bow the Iron Mine to produce 2 Gold.\nIf a Crab Clan player controls the Iron Mine, it produces 3 Gold.');
INSERT INTO holdings VALUES ('Island Wharf', '1', '1', '1', null, null, 'The Island Wharf is considered a Port.\nBow the Island Wharf to produce 1 Gold.\nIf a Yoritomo\'s Alliance player controls the Island Wharf, it produces 2 Gold when bowed.');
INSERT INTO holdings VALUES ('Jade Works', '1', '3', '3', null, null, 'Bow the Jade Works to produce 3 Gold.\nBow the Jade Works to produce 5 Gold when paying for a Jade card.');
INSERT INTO holdings VALUES ('Marketplace', '1', '2', '2', null, null, 'Bow the Marketplace to produce 2 Gold.\nIf you are a Crane player the Marketplace produces 3 Gold when bowed.');
INSERT INTO holdings VALUES ('Pearl Bed', '1', '2', '1', null, null, 'Bow the Pearl Bed to produce 1 Gold.  If a Naga player controls the Pearl Bed, it produces 2 Gold when bowed.  It produces 1 additional Gold when bowed for each Pearl Divers in play.');
INSERT INTO holdings VALUES ('Pearl Divers', '1',  '1', '1', null, 'Retainer', 'Bow Pearl Divers to produce 1 Gold, plus 1 Gold for each Port in play.');
INSERT INTO holdings VALUES ('Pitfall', '1', '3', null, null, 'Fortification', 'Immediately before the Resolution Segement of a battle at this Province, give +5F to a defending Personality in this batle until the Resolution Segment ends.');

/* Insert into Follower table */
INSERT INTO followers VALUES ('Archers', '2', '0', '0', null, '4', '1', 'Battle', 'Battle: Bow Archers for a Ragned 3 Attack.', '2');
INSERT INTO followers VALUES ('Goblin Berserkers', '2', '0', '0', null, '0', '0', 'Nonhuman, Shadowlands, Battle', 'Lose 2 Honor.\nBattle: Destroy the Goblin Berserkers.  Return this unit to your fief.  You can take this action even if the Berserker\'s Personality is bowed.', '0');
INSERT INTO followers VALUES ('Goblin Chuckers', '2', '2', '0', null, '0', '0', 'Nonhuman, Shadowlands, Battle', 'Lose 2 Honor.\nBattle: Bow for a Ranged 2 Attack.', '2');
INSERT INTO followers VALUES ('Goblin Mob', '2', '1', '0', null, '0', '0', 'Nonhuman, Shadowlands, Reaction', 'Lose 2 Honor.\nReaction: When a ranged attack targets a card in this unit, the ranged attack targets the Goblin Mob instead.', '0');
INSERT INTO followers VALUES ('Light Cavalry', '2', '1', '0', null, '2', '1', 'Cavalry', null, '1');
INSERT INTO followers VALUES ('Medium Cavalry', '2', '2', '0', null, '5', '1', 'Cavalry', null, '2');
INSERT INTO followers VALUES ('Ambush Strategist', '2', '2', '0', null, '6', '1', 'Battle', 'Battle: Bow the Ambush Strategist to give each card in this unit with one or more ranged attackes a Force bonus equal to the card\'s highest non-variable Ranged Attack strength.', '2');
INSERT INTO followers VALUES ('Armored Steeds', '2', '3', '0', null, '7', '2', 'Cavalry, Battle', 'Battle: Bow Armored Steeds to take two consecutive Open or Battle actions after this one.', '3');
INSERT INTO followers VALUES ('Brothers of Thunder', '2', '1', '0', null, '3', '1', null, 'Only a Monk Personality can attach the Brothers of Thunder.  The Brothers have +1F for each Elemental Ring you have in play.', '2');
INSERT INTO followers VALUES ('Clay Soldiers', '2', '1', '0', null, '0', '1', null, 'Only a Shugenja Personality can attach Clay Soldiers.', '1');
INSERT INTO followers VALUES ('Elite Spearmen', '2', '2', '0', null, '2', '4', 'Battle', 'Battle: Ranged 2 Attack (Destroy a target enemy Follower or Personality without Followers with 2 or lower Force.', '3');
INSERT INTO followers VALUES ('Greensnake', '2', '1', '0', null, '2', '1', 'Naga, Open', 'Open: Bow a Forest in play.  Greensnake gains +1F.  You cannot bow another player\'s Forest during the player\'s turn.', '2');
INSERT INTO followers VALUES ('Heavy Infantry', '2', '5', '0', null, '8', '1', null, null, '2');
INSERT INTO followers VALUES ('Hurricane Initiates', '2', '2', '1', null, '7', '1', 'Shugenja, Cavalry, Limited', 'Limited: Target a unit.  Bow the Hurricane Initiates to give the Cavalry trait to the Personality and Followers in the target unit until the turn ends.', '3');
INSERT INTO followers VALUES ('Kaiu Siege Engine', '2', '1', '0', null, '5', '1', 'Battle', 'A Kaiu Personality attaches the Siege Engine for 2 less Gold.  You cannot commit this unit during the Cavlary Maneuvers Segment.\nBattle: Bow to destroy a Fortification attached to this Province.\nBattle: Bow to lower this Province\'s Strength by 4 (minimum 0).', '1');
INSERT INTO followers VALUES ('Moto Chargers', '2', '2', '0', null, '4', '1', null, 'When a card effect moves this unit into battle, Moto Chargers gain +2F.', '3');
INSERT INTO followers VALUES ('Naga Bushi', '2', '2', '0', null, '3', '1', 'Naga', null, '2');
INSERT INTO followers VALUES ('Oni no Megada', '2', '2', '-1', null, '2', null, 'Nonhuman, Shadowlands', 'Lose 2 Honor.\nOni no Megada gains +3F while targeted by a ranged attack.', '2');
INSERT INTO followers VALUES ('Ratling Bushi', '2', '3', '0', null, '6', '0', 'Creature', 'Ratling Bushi gains +1F for each Ratling Pack in this unit.', '0');
INSERT INTO followers VALUES ('Spirit Hounds', '2', '0', '0', null, '4', '1', 'Spirit, Battle', 'Battle: Fear 3.  Spirit Hounds gain +1F until this battle ends for each card bowed by this Fear.', '2');

/* Insert into Attachments table */
INSERT INTO attachments VALUES ('Armor of Earth', '2', '1', '2', '8', 'Unique, Elemental, Reaction', 'While you have a Ring of Earth in play, Armor of Earth gains a +2F/+1C bonus and has a printed Gold cost of 0.\nElemental Reaction: Cancel an acion moving this unit out of a battle it assigned to during this attack.', '3'); 
INSERT INTO attachments VALUES ('Ashigaru Armor', '2', '0', '1', '1', null, 'You may draw an extra card during yout next End Phase after bringing this card into play from your hand. Ashigaru Armor\'s cost may not be reduced. Ashigaru Armor gains +1F while opposed in a battle.', '1');
INSERT INTO attachments VALUES ('Blackened Claws', '2', '1', '1', '4', 'Shadowlands, Reaction', 'Cannot be moved. May only attach to a Shadowlands Personality without Blackened Claws.  May attach to a Personality regardless of restrictions on the Personality.\nReaction: When this Personality enters a duel, bow Blackened Claws to give two -1C Corruption tokens to the opposing Personality.', '2');
INSERT INTO attachments VALUES ('Bone of the Tattered Ear Tribe', '2', '2', '2', '7', 'Weapon, Unique, Limited', 'When Bone of the Tattered Ear Tribe enters play, it gives a +1F/+1C Pack token to each Ratling Follower you control.\nLimited: Bow Bone of the Tattered Ear Tribe and remove a Pack token from it to search any player\'s Fate discard pile for a Follower and put it in your hand, face-up and revealed to all players.  Lose 3 Honor.', '4');
INSERT INTO attachments VALUES ('Celestial Sword of the Crab', '2', '0', '1', '8', 'Weapon, Unique', 'If you are a Crab Clan player, gain 2 Honor.  Celestial Sword of the Crab counts as the Ancestral Sword of the Crab Clan for uniqueness.\nWhile attached to a Crab Clan Personality, Celestial Sword of the Crab gains +1F/+1C for each Crab Clan Personality you control.', '4');
INSERT INTO attachments VALUES ('Celestial Sword of the Crane', '2', '0', '1', '8', 'Weapon, Unique', 'If you are a Crane Clan player, gain 2 Honor.  Celestial Sword of the Crane counts as the Ancestral Sword of the Crane Clan for uniqueness.\nWhile attached to a Crane Clan Personality, Celestial Sword of the Crane gains +1F/+1C for each Crane Clan Personality you control.', '4');
INSERT INTO attachments VALUES ('Celestial Sword of the Lion', '2', '0', '1', '8', 'Weapon, Unique', 'If you are a Lion Clan player, gain 2 Honor.  Celestial Sword of the Lion counts as the Ancestral Sword of the Lion Clan for uniqueness.\nWhile attached to a Lion Clan Personality, Celestial Sword of the Lion gains +1F/+1C for each Lion Clan Personality you control.', '4');
INSERT INTO attachments VALUES ('Clay Horse', '2', '0', '0', '2', 'Reaction', 'Reaction: After a battle ends, bow Clay Horse to prevent this unit from being bowed by the battle.  Reveal and discard the top card of your Fate deck..  If its Focus Value is odd, destroy Clay Horse.', '2');
INSERT INTO attachments VALUES ('Dai Tsuchi', '2', '3', '0', '6', 'Weapon', 'Will only attach to a Personality with more than 2 Force.  Crab Clan Personalities can attach Dai Tsuchi for 2 less Gold.  Dai Tsuchi gains a +3C bonus while this Personality opposses one or more Ogres or Oni in a battle or duel.', '1');
INSERT INTO attachments VALUES ('Fan of Command', '2', '0', '0', '4', null, 'This Personality gains Tactician while Fan of Command is attached.', '2');
INSERT INTO attachments VALUES ('Ichiro\'s Yumi', '2', '0', '0', '3', 'Weapon, Battle', 'Will only attach to a Samurai or Bushi.\nBattle: Bow Ichiro\'s Yumi to give -3F to an opposing Follower or Personality.  You may then produce a Ranged 0 Attack against that card if it is a legal target.', '2');
INSERT INTO attachments VALUES ('Kaimetsu-uo\'s Blade', '2', '1', '1', '3', 'Weapon, Battle', 'Battle: Target an opposing Item and its Personality.  Bow Kaimetsu-uo\'s Blade and move it onto that Personality (even if he already has a weapon) to move that item to this Personality. Lose 3 Honor if you are not a Ratling Player.', '2');
INSERT INTO attachments VALUES ('Layered Armor', '2', '1', '2', '1', 'Reaction', 'Reaction: Bow Layered Armor to negate a Ranged attack targeting this Personality.', '2');
INSERT INTO attachments VALUES ('Mempo of the Void', '2', '1', '2', '9', 'Unique, Elemental, Open', 'While you have a Ring of the Void in play.  Mempo of the Void gains a +2F/+1C bonus and has a printed Gold cost of 0.\nElemental Open: Bow Mempo of the Void and discard any number of cards from your hand to draw an equal number of cards from your Fate deck.', '3');
INSERT INTO attachments VALUES ('My Father\'s Weapon', '2', '1', '1', '3', 'Weapon', 'Straighten this Personality at the end of the turn you bring My Father\'s Weapon into play.', '3');
INSERT INTO attachments VALUES ('Peasant Weapons', '2', '2', '2', '6', 'Battle', 'Costs 1 less Gold when attaching to a Monk. Dishonor this Personality unless he is Mantis Clan or a Monk.\nBattle: Destroy Peasant Weapons to send an item on an opposing Personality to its owner\'s hand.  If Peasant Weapons was attached to a Monk, you may then take an additional Battle Action.', '3');
INSERT INTO attachments VALUES ('Scroll Satchel', '2', '0', '1', '2', 'Reaction', 'Reaction: After a Spell attached to this Personality is destroyed, bow Scroll Satchel to attach a Spell to this Personality from your hand, paying all costs.  Reduce that Spell\'s Gold cost by 2.\nReaction: After this Personality attaches a Spell, destroy Scroll Satchel to draw a card.', '2');
INSERT INTO attachments VALUES ('Yoritomo\'s Kama', '2', '2', '2', '6', 'Weapon, Unique', 'Other weapons in this army gain a +1F/+1C bonus.', '4');
INSERT INTO attachments VALUES ('Blade of the Master', '2', '0', '1', '2', 'Weapon, Battle', 'Battle: Destroy this card: Target an opposing Personality.  The Personality\'s controller targets a Personality in this army with lower Chi.  The first Personality issues the second an unrefusable Challenge.', '3');
INSERT INTO attachments VALUES ('Gunsen-gata', '2', '2', '0', '3', null, 'If you are a Lion Clan player, this card counts as a Follower, a weapon, and an armor (as well as an action) for satisfying "Formed By" requirements.', '3'); 

/* Insert into MonkShugenjaAttachments table */
INSERT INTO monk_shugenja_attachments VALUES ('The Kami\'s Embrace', '2', '4', 'Air, Water, Fire, Earth, Open, Battle', 'Each ability on this Spell has "Bow this Spell" as a base cost and can only be performed by a Shugenja who shares an Element Keyword with it.\nAir Open: Turn all face-down cards in your provinces face-up.\nEarth Battle: Bow a target Personality at this location with less Chi.\nFire Battle: Ranged 6 Attack.\nWater Battle: Move a target unit from the current battlefield to another location.', '4');
INSERT INTO monk_shugenja_attachments VALUES ('Purge the Unclean', '2', '1', 'Fire, Battle', 'Fire Battle: Bow this Shugenja, or bow this Spell if attached to a Fire Shugenja: Destroy one or more target attachments opposing this card up to the number of different Element keywords on cards in this Shugenja\'s army.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Purge the Weak', '2', '1', 'Maho, Reaction', 'Maho Reaction: After one of your Limited, Open, or Battle Actions resolves, permanently give this Shugenja -1C: Take an additional action with the same designator (Limited, Open, or Battle).', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Touch of Ice', '2', '2', 'Water, Open', 'This Spell cannot have its gold cost reduced, Water Open: If it is not your turn, bow this Shugenja: Another target Player may choose to bow 2 of his Personalities.  If he does not bow 2 Personalities, gain 3 Honor.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Yuki no Onna\'s Wrath', '2', '3', 'Water, Battle', 'Water Battle: Bow this Shugenja: Destroy a target card without attchents opposing this Shugenja.  You may destroy a Terrain.', '2');
INSERT INTO monk_shugenja_attachments VALUES ('The Elements\' Path', '2', '0', 'Kiho, Open', 'Kiho Open: Target one of your Monks and one of your non-void Rings: Permanently copy an ability from the Ring to the Monk.  The Monk permanently need not bow to pay costs of copied action.', '2'); 
INSERT INTO monk_shugenja_attachments VALUES ('Hitsu-do', '2', '0', 'Kiho, Fire, Battle', 'Kiho Fire Battle: Bow and destroy one of your target Shugenja of Monks: target an enemy Follower, or an enemy Personality with no Followers: the Personality, or Follower\'s Personality must have equal or lower Chi than yours.  Destroy the enemy target.', '4');
INSERT INTO monk_shugenja_attachments VALUES ('Inspire Courage', '2', '0', 'Kiho, Fire, Open', 'Kiho Fire Open: Bow one of your target Monks or Shugenja: give one to three target Samurai Personalities +2F.  If the performer has the Fire Keyword, the Samurai can not move home from battlefields this turn.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Inspire Fear', '2', '0', 'Kiho, Fear, Water, Battle', 'Kiho Fear Water Battle: Target one of your unbowed Monks or Shugenja: Move home a target human Personality opposing him.  If the performer has the Water Keyword, the Personality cannot move to battlefields this turn.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Master of the Rolling River', '2', '0', 'Kiho, Water, Battle', 'Kiho Water Battle: Bow one of your taret Shugenja of Monks at any location: Move one of your target units at a battlefield to a different battlefield.', '2');
INSERT INTO monk_shugenja_attachments VALUES ('Sap the Spirit', '2', '0', 'Kiho, Open', 'Kiho Open: Target one of your Shugenja or Monks: Units cannot assign in cavalry maneuvers this turn.\nKiho Open: Target one of your Shugenja or Monks: A target Stronghold\'s ability cannot be used until your next turn begins.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Strike of the Dragon', '2', '0', 'Kiho, Battle', 'Kiho Battle: Bow one of your Rings and one of your target Monks: Bow one to three target Personalities opposing him, each with Force higher than his own Chi.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Purity of the Seven Thunders', '2', '3', 'Ritual, Limited', 'Ritual Limited: Bow this Shugenja, and any number of your other Shugenja, such that their combined Chi is greater than 14, and destroy this Spell and this Shugenja, to destroy all Shadowlands cards.  The Shugenja in this Rtual cannot straighten during your next turn.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Sezumi\'s Punishment', '2', '2', 'Limited, Open', 'Limited: Bow this Shugenja and destroy this Spell to permanently remove a Maho Action from a card.\nOpen: Once per turn, without bowing, destory a Token.', '2');
INSERT INTO monk_shugenja_attachments VALUES ('Tomb of Jade', '2', '5', 'Limited', 'Limited: Bow ths Shugenja and destory this Spell to destroy a Shadowlands card.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Touching the Elements', '2', '2', 'Air, Earth, Fire, Water, Open, Battle', 'Air Open: Bow this Spell to turn one face-down card in a Province face-up.\nEarth Open: Bow this Spell to give a Personality +1F.\nFire Battle: Bow this Spell for a Ranged 1 attack.\nWater Open: Bow this Spell to a Personality +1C.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Walking the Way', '2', '4', 'Limited', 'Limited: Bow this Shugenja and destroy this Spell to search your Fate deck for any one card and put it into your hand.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Contagion', '2', '0', 'Maho, Kiho, Battle', 'Maho Kiho Battle: Bow one of your Shugenja or Monks to target a Personality.  Contagion destroys any number of cards attached to that Personality, determined by his controller.  Then Contagion gives the Personality -3C for each card still attachedto him.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Dharma Technique', '2', '0', 'Kiho, Reaction', 'Kiho Reaction: After an Event is revealed, but before it resolves, bow one of your Monks to discard the Event without resolution.', '3');
INSERT INTO monk_shugenja_attachments VALUES ('Fall Before the Master', '2', '0', 'Kiho, Open', 'Kiho Open: Target one of your unbowed Monks.  After each duel he wins this turn, he permanently gains +2F/+2C nad you may draw a card.', '3');

/* Insert into Stronghold table */
INSERT INTO strongholds VALUES ('Kyuden Hida', '0', '8', '4', '3', 'Shadowlands, Experienced, Recon Reaction', 'Recon Reaction: After engaging, target the current battlefield\'s Province: Create and attach a 0F Scout Follower to each one of your Personalities in your current army.  Remove these Followers from the  game after this battle ends.', 'Crab'); 
INSERT INTO strongholds VALUES ('Razor\'s Edge Dojo', '0', '8', '4', '3', 'Battle', 'The first time each phase each other player targets one of your Personalities with an action, he must discard a card from his hand.\nBattle: Bow Razor\'s Edge Dojo to giveeach of your Crab Clan Personalities in the current battle +1F.', 'Crab');
INSERT INTO strongholds VALUES ('Kaiu Shiro', '0', '8', '4',  '3', null, 'Your Hero Personalities have Yu +1 and a minimum Yu of 3.\nOnce per phase, after another player\'s action resolved which destroyed one of your Personalities: Destroy a target Follower, or a target Personality without Followers, with Force less than or equal to your Personality\'s Yu value.  If during a battle, the target must be in the enemy army.', 'Crab'); 
INSERT INTO strongholds VALUES ('Kosaten Shiro', '0', '5', '4','6', null, 'Gold- and Honor-producing Holdings cost 1 less Gold for you, to a minimum of 0, but cannot have their costs changed in any other way.', 'Crane');
INSERT INTO strongholds VALUES ('Kyuden Doji', '0', '6', '4', '6', 'Political, Reaction, Limited', 'Political Reaction: When one of your Personalities enters a duel, target and bow one of your Crane Clan Samurai to have that Samurai enter the duel instead.\nPolitical Limited: Bow Kyduen Doji to permanently give Courtier to one of your Crane Clan Personalities.', 'Crane');
INSERT INTO strongholds VALUES ('Kakita Dueling Academy', '0', '7', '4', '5', 'Political, Limited', 'Political Limited: Bow Kakita Dueling Academy to search your Fate deck for an Iaijutsu Action card.  show the card to the other players and add it to your hand.', 'Crane');
INSERT INTO strongholds VALUES ('Temples of the Crow', '0', '6', '4', '4', 'Limited', 'Limited: Bow the Temples ofthe Crow and discard one of your Sensei in play to bring a Sensei into play from your deck or hand.  If the Sensei comes from the deck, reshuffle the deck.', 'BotS');
INSERT INTO strongholds VALUES ('Vigilant Keep of the Monkey', '0', '7', '4', '5', null, 'Your Human Personalities each gain +1C.  You may ignore Follower\'s Honor requirements.', 'Toturi\'s Army');
INSERT INTO strongholds VALUES ('The New Akasha', '0', '6', '3', '2', null, 'Crab Personalities will join you for 2 less Gold, but cannot have their Gold cost further reduced.  You may ignore Honor requirements for Crab Personalities and Naga cards if you have no Shadowlands cards in play.  If you have both Naga Personalities and Crab Personalities in the same army, each such Personality gains +1F/+1C.  Your Naga cards are immune to Fear.', 'Naga');
INSERT INTO strongholds VALUES ('Mountain Summit Temple', '0', '7', '4', '5', 'Limited', 'Limited: Bow one of your target Monk Personalities: Put one of your Rings from your hand into play, from play into your hand, or from your discard pile into your hand.', 'Dragon');
INSERT INTO strongholds VALUES ('Tetsu Kama Mura', '0', '8', '4', '5', 'Limited', 'Before you draw a card: You may draw it from the bottom of your deck.\nLimited: Look at the top card of your Fate deck.  You may put it at the bottom of your deck.', 'Dragon');
INSERT INTO strongholds VALUES ('Kyuden Ikoma', '0', '5', '3', '5', 'Reaction', 'Reaction: Bow your Stronghold to cancel a Battle action.  If it\'s an action card, its player may return it to his hand after the battle.  The player may immediately take another action.', 'Lion');
INSERT INTO strongholds VALUES ('Crossroads Fortress', '0', '7', '3', '7', 'Reaction', 'Reaction: After you assign an attacking unit, discard a card.  Draw a card.', 'Lion');
INSERT INTO strongholds VALUES ('Shamate Keep', '0', '7', '3', '7', 'Battle', 'Your Paragons have a minimum Personal Honor equal to their base Personal Honor.\nBattle: Choose your performing unbowed Personality and target a Personality with equal or lower Personal Honor: Move him home.  Gain 2 Honor if you do not control him.', 'Lion');
INSERT INTO strongholds VALUES ('Aramasu\'s Pride', '0', '8', '4', '2', 'Raid, Limited', 'Raid Limited: ONce per turn, declare an additional Attack Phase.  This is a Raid Attack.  During it, battles are Raid Battles and battle resolution does not destroy armies or Provinces and does not bow Pirate cards.  After it, target a number of Holdings up to the number of battles you won (even against no units at resolution).  Raise their Gold Production by 4.', 'Mantis');
INSERT INTO strongholds VALUES ('Eastern Hub Port', '0', '7', '4', '2', null, 'Equipping is Battle/Open action for you.\nAfter the first battle action resolution each turn that attached a card to one of your Personalities: You may take an additional battle action.', 'Mantis');
INSERT INTO strongholds VALUES ('Kyuden Ashinagabachi', '0', '7', '4', '2', null, 'After each of your Ranged Attacks resolves: If it did not destroy its target, reduce the target\'s Force by the Ranged Attack\'s strength.', 'Mantis');
INSERT INTO strongholds VALUES ('Towers of Asako', '0', '5', '3', '6', 'Reaction', 'Reaction: When an action targets one of your Shugenja Personalities bow the Towers of Asako to cancel it.\nReaction: When an action targets one of your Samurai bow one of your Shugenja Personalities to cancel it.', 'Phoenix');
INSERT INTO strongholds VALUES ('The Agasha Foundries', '0', '6', '4', '6', 'Reaction', 'Equipping Spells that share an Elemental keyword with their Shugeja is an Open action for you.\nReaction: Even if this Stronghold is bowed, after a Shugenja bows as a cost of performing an action on a Spell: Straighten him.', 'Phoenix');
INSERT INTO strongholds VALUES ('Kyuden Asako', '0', '6', '4', '6', 'Reaction, Open', 'Reaction: After one of your Temples bows: Straighten one of your target Shugenja.\nOpen: Bow one of your target Shugenja or Monks: Straighten one of your target Temples.', 'Phoenix');
INSERT INTO strongholds VALUES ('Warrens of the Nezumi', '0', '13', '3', '1', null, 'You begin the game with three Provinces.\nNon-Personality Rattling cards cost 1 less Gold for you.  Your Rattling cards cannot gain Shadowlands, are immune to Fear, and have the ability, "Battle: Bow and destroy this card to destroy an opposing Follower.', 'Rattling');
INSERT INTO strongholds VALUES ('Kyuden Bayushi', '0', '7', '4', '2', 'Political, Reaction', 'You may have two different Winds.\nPolitical Reaction: Once per turn, bow one of your Scorpion Clan Personalities to pay a cost of discarding the Imperial Favor.  This may be used while bowed.', 'Scorpion');
INSERT INTO strongholds VALUES ('The Ruined City', '0', '8', '4', '0', null, 'You do not lose Honor from Fate and Spider Clan cards you own.\nYour Spider Clan Personalities have the ability, "Battle: Bow a target unit with zero total Force or with the lowest non-zero Force (including ties) among all units at the current battlefield.', 'Spider');
INSERT INTO strongholds VALUES ('The Temple of Death', '0', '7', '5' ,'4', 'Battle, Open', 'Battle: Remove a Personality in any discard pile from the game: Bow a target Personality.\nOpen: Remove a Personality in any discard pile from the game: Straighten a target Personality.', 'Unicorn');
INSERT INTO strongholds VALUES ('The Utaku Plains', '0', '7', '5', '4', 'Battle', 'Your Personalities have +1 PH nad a maximum Personal Honor of 5 while in play.\nBattle: Target one of your Personalities: Reduce the Force of a target Personality or Follower opposing him by your Personality\'s Personal Honor.', 'Unicorn');

/* Insert into Winds table */
INSERT INTO winds VALUES ('Balck Heart of the Empire', '0', 'Daigotsu, Battle', 'Lobbying is not Political for you.  You lobby by bowing a Shadowlands Personality regardless of Personal Honor.  For purposes of any player lobbying against your Family Honor is considered to be the total printed Force of your Personalities if that total is higher than each other player\'s.\nBattle: Discard the Imperial Favor to reduce the Force of one opposing card to 0.');
INSERT INTO winds VALUES ('Left Hand of the Emperor', '0', 'Toturi Tsudao, Political, Battle, Reaction', 'Political Battle: Discard the Imperial Favor to send an attacking unit home.  You may use this in a battle in which you have no units.\nPolitical Reaction: Once per turn, after one of your Samurai dies as the result of a battle, or duel, bow your Stronghold or a Courtier to gain 2 Honor.');
INSERT INTO winds VALUES ('Right Hand of the Emperor', '0', 'Akodo Kaneka, Political, Battle, Reaction', 'Political Battle: Discard the Imperial Favor to move a unit you control from one of the Defender\'s Provinces to another.\nPolitical Reaction: Once per turn, when one of your Personalities is moving into or out of a battle, bow your Stronghold or a Courtier to negate that movement.');
INSERT INTO winds VALUES ('Underhand of the Emperor', '0', 'Hantei Naseru, Political, Open, Reaction', 'Political Open: Discard the Imperial Favor and name a Political Action card.  Search your Fate deck for the card, show it to all players, and add it to your hand.  Each card title may be named once per turn.\nPolitical Reaction: Once per turn, after a player has declared an attack, bow one of your Courtiers to target one of the Attacker\'s Samurai with less Personal Honor.  That Samurai cannot assign to an army this attack.'); 
INSERT INTO winds VALUES ('Voice of the Emperor', '0', 'Toturi Sezaru, Political, Limited', 'Political Limited: Discard the Imperial Favor to draw a Fate card.\nPolitical Limited: Once per turn, bow your Stronghold or a Courtier to put an Elemental Ring into play from your hand.  While in play, that Ring does not count towards an Enlightenment Victory, and at hte beginning of each of yout turns, discard a card from your hand or shuffle the Ring back into your Fate deck.');
INSERT INTO winds VALUES ('Akodo Kaneka', '0', 'The Bastard, Political, Limited', 'Political Limited: Discard the Imperial Favor to place one or more face-up Dynasty cards in your Provinces face-down at the bottom of your Dynasty deck and replace them with face-up Dynasty cards.  Discard any Events revealed this way, and replace them with face-down Dynasty cards.');
INSERT INTO winds VALUES ('Hantei Naseru', '0', 'The Anvil, Political, Reaction, Open', 'Political Reaction: Before any player loses Honor, discardthe Imperial Favor to negate the loss.\nPolitical Reaction: When your turn begins, discard the Favor to name a phase.  Until your next turn begins, lower all Honor gains by half, rounded down, during that phase of each player\'s turn.\nPolitical Open: Discard the Imperial Favor to restore a Dishonored Personality to Honorable status.');
INSERT INTO winds VALUES ('Toturi Tsudao', '0', 'The Sword, Political, Battle', 'Political Battle: Discard the Imperial Favor to send an attacking or allying unit home from this battle, bowed.  You may take this action during a battle in which you have no units.');
INSERT INTO winds VALUES ('Toturi Sezaru', '0', 'The Wolf, Political, Limited', 'Political Limited: Discard the Imperial Favor to draw an extra card during your next End Phase.');

/* Insert into Sensei table */
INSERT INTO senseis VALUES ('Akodo Sensei', '0', '0', '0', '0', 'Crane, Dragon, Lion, Sensei', 'Your Dishonored Personalities always have 0 Force.  Each of your Samurai with over 2 Chi and without the Tactician trait gains the Tactician trait, but cannot use it to gain Force bonuses.');
INSERT INTO senseis VALUES ('At\'tok\'tuk Sensei', '0','0','0','-2', 'Crab, Mantis, Monk, Ninja, Shadowlands, Unicorn, Sensei', 'Your Ratling Personalities are memebers of your clan.  Ratling Followers will join you for 1 less Gold.');
INSERT INTO senseis VALUES ('Gozoku Sensei', '0', '0', '0', '0', 'All Factions, Sensei, Political, Open, Reaction', 'You may not play this card if you have a Wind.\nPolitical Open: Discard the Favor to bow a Personality.  He may not straighten until after you discard the Favor again or his controller pays 6 Gold as an Open action.\nPolitical Reation: Once per turn, before any player gains or loses Honor, bow your Stronghold or one of your Courtiers to reduce the loss or gain by 2.');
INSERT INTO senseis VALUES ('Hantei Sensei', '0', '0', '0', '0', 'All Clans, Sensei, Limited', 'Limited: Once per game, target another player and name a non-Elemental Ring Fate card.  For the rest of the game, the player cannot use any copy of the card except for its Focus Value.  The player may name a non-Elemenetal Ring Fate card that you cannot use for the rest of the game except for its Focus Value.');
INSERT INTO senseis VALUES ('Satsuma Sensei', '0', '0', '0', '0', 'All Clans, Sensei', 'Players cannot attach any Followers to any Personality with less Chi than the Follower\'s Force.  None of your Personalities can attach Followers whose Force exceeds the Personality\'s Personal Honor.');
INSERT INTO senseis VALUES ('Seppun Sensei', '0', '0', '0', '0', 'All Clans, Sensei', 'You cannot take actions that would cause Honor losses for other players.  Your Honor losses and gains cannot e changed, redirected, or copied.');
INSERT INTO senseis VALUES ('Tadaji Sensei', '0', '0', '0', '0', 'Unicorn Clan, Sensei', 'Personalities with a printed Personal Honor liess than 2 will not join you.  After each time an army containing your units wins a battle or destroys a Province (or both), you may gain Honor equal to the number of battle maidens you control in that army.');
INSERT INTO senseis VALUES ('Tishi Sensei', '0', '0', '0', '-1', 'Scorpion Clan, Sensei, Open', 'Your Honor gains have a maximum value of 1.  Ninja you own have +1C.\nOpen: Once per turn, bow one of your Scorpion Clan Personalities to look at a number of face-down cards in an opponent\'s hand or Provinces up to your Personality\'s Chi.');
INSERT INTO senseis VALUES ('Uona Sensei', '0', '0', '0', '0', 'Crane, Dragon, Monk, Phoenix, Sensei, Limited', 'You cannot get cards from your discard piles or from anywhere in your decks except the top.\nLimited: Once per turn, look at your Dynasty or Fate deck\'s top card.  You may discard the card.');
INSERT INTO senseis VALUES ('Wasp Sensei', '0', '0', '0', '0', 'All Clans, Sensei', 'Your Wasp Clan Personalities have your Clan\'s trait.  Human Followers with Ranged attacks cost 2 less Gold, to a minimum of 1, for you.  You cannot lobby for the Imperial Favor.');

/* Insert into Ring table */
INSERT INTO rings VALUES ('Ring of Air', '2', 'Air, Unique, Battle, Open', 'After you resolve your third or later Spell or Kiho Action in one turn from cards with different titles: You may put this card into play from your hand.\nBattle/Open: Bow this card or discard it from your hand: Straighten a target Personality.', '4');
INSERT INTO rings VALUES ('Ring of Earth', '2', 'Earth, Unique, Battle, Open', 'After you destroy one or more provinces or enemy units by winning a battle at a province: You may put this card into play from your hand.\nBattle/Open: Bow this card or discard it from your hand: Raise a target Province\'s strength by 4; you may instead lower its strength by 3 if this card is in play.', '4');
INSERT INTO rings VALUES ('Ring of Fire', '2', 'Fire, Unique, Focus Effect, Battle', 'Focus Effect: You may give this card -2 Focus Value.  If you do, after the duel ends, put this card into play if you win this duel during a battle.\nBattle: Bow this card or discard it from it from your hand, and destroy your target Personality: Destroy a target Pesonality with lower Chi.', '4');
INSERT INTO rings VALUES ('Ring of Water', '2', 'Water, Unique, Battle', 'After you resolve your fourth of later battle actoin from cards with different titles in one battle: You may put this card into play from your hand.\nBattle: Bow this card or discard it from your hand: Move your target unit home or to a battlefield with one or more enemey units.  If the unit moved, straighten it.', '4');
INSERT INTO rings VALUES ('Ring of the Void', '2', 'Void, Unique, Open', 'After you succesfully resolve yout fourth or later non-Kiho action from action cards in one phase: You may pur this card into play from your hand.\nOpen: Bow this card or discard it from your hand: If any player has more cards in his hand than you do, or if you bowed this card, draw a card.', '4');

/* Insert into Action table */
INSERT INTO acts VALUES ('Three-Stone River', '2', '0', 'Terrain, Battle', 'Terrain Battle: Before this battle\'s resolution, reduce the Force of each Personality at this battlefield to the Force of his highest-Force Follower, or to 1 if he has no Followers.', '1');
INSERT INTO acts VALUES ('Guard the House', '2', '0', 'Reaction', 'Reaction: Play this card when one of your Provinces is destroyed.  Permanently raise the Strength of eah of your other Provinces by 2.', '1');
INSERT INTO acts VALUES ('Iaijutsu Duel', '2', '0', 'Battle', 'Battle: A Personality in your army issues an unrefusable challenge to an opposing Personality.  You need not control either Personality.  If the Personality in your army is not yours and the challenge gains a cost, the controller of the Personality may choose to not pay the cost and send this card back to your hand.  The winner\'s controller gains 5 Honor.', '2');
INSERT INTO acts VALUES ('Interruption', '2', '0', 'Open', 'Open: Straighten another player\'s Personality.  You may take this action during a battle in which you have no units.', '3');
INSERT INTO acts VALUES ('Last Gift', '2', '0', 'Political, Open', 'Open: Permanently give a target Human Personality +1PH.', '3');
INSERT INTO acts VALUES ('Moto Technique', '2', '0', 'Reaction', 'Reaction: Play this card face up as a Focus card in a duel.  Bow both Personalities in the duel.  If your Personality is Moto and has higher Force than the other Personality, your Personality straightens.', '2');
INSERT INTO acts VALUES ('Personal Sacrifice', '2', '0', 'Reaction', 'Reaction: Play this card after one of your Personalities strikes in a duel during battle, if the Personality did not focus.  If the Personality is destroyed during the duel, each of your Personalities permanently gains +1F/+1C.', '3');
INSERT INTO acts VALUES ('Rallying Cry', '2', '0', 'Reaction', 'Reaction: Play this card after a Resolution Segment.  Your units in the battle do not become bowed by the combat.', '3');
INSERT INTO acts VALUES ('Nezumi Technique', '2', '0', 'Battle', 'Battle: Bow one of your Personalities in the current battle to destroy an opposing Item.  If your Personality is a Ratling straighten him and draw a card.', '3');
INSERT INTO acts VALUES ('Open Warfare', '2', '0', 'Political, Open', 'Political Open: Bow your Stronghold during the Action Phase to target another player\'s Stronghold.  Until the end of the turn, that Stronghold\'s actions cannot be used, and its traits have no effect except those involving victory or elimination conditions or changes to that player\'s Family Honor.', '2');
INSERT INTO acts VALUES ('No Hiding Place', '2', '0', 'Reaction', 'Reaction: After you announce an action with a Ranged Attack: Give one Ranged Attack from the action -1 strength. That Ranged Attack may target a card in the Defender\'s home (if otherwise legal).', '3');
INSERT INTO acts VALUES ('Bayushi\'s Knives', '2', '0', 'Flanking Formation, Battle', 'Formed by 4 Personalities or 2 Ninja Personalities.\nBattle: Discard an Action card from your hand to straighten a Personality in this battle.  This may target each Personality once.\nBattle: Destroy one of your Ninjas in this battle to send all your units home from this battle.', '2');
INSERT INTO acts VALUES ('Block Supply Lines', '2', '0', 'Battle', 'Battle: Move home a target attacking Personality.  Bow his unit as he moves.', '3');
INSERT INTO acts VALUES ('Destiny Has No Secrets', '2', '0', 'Battle', 'Battle: Give your target Personality +2F/+2C.  Show your hand to all players.', '1');
INSERT INTO acts VALUES ('Encirlced Terrain', '2', '0', 'Terrain, Battle', 'Before this battle resolves, the Attacker and Defender, in the order of your choice, each choose one of their own Personalities at its battlefield.  Move all other Personalities there home.\nBattle: Destroy a Terrain (if able).  Put this Terrain into play.', '1');
INSERT INTO acts VALUES ('Hazardous Ground', '2', '0', 'Battle, Terrain', 'You may only play this card if you have a Samurai in this battle with a Chi of 4 or more.\nBattle Terrain: This terrain takes effect as soon as it is played.  Beginning with your next opportunity to perform an action, whenever it is your turn to perform an action in this battle, you may perform two actions instead of one.', '1');
INSERT INTO acts VALUES ('Occupied Terrain', '2', '0', 'Battle, Terrain', 'During the resolution phase, if the Defender\'s Province is being destroyed, the Attacking Player may select one of the Defender\'s holdings which is destroyed instead of the Province.', '1');
INSERT INTO acts VALUES ('Entrapping Terrain', '2', '0', 'Delayed Terrain, Battle', 'Battle: This battle ends without resolution.  All units go home without bowing.', '1');
INSERT INTO acts VALUES ('Superior Tactics', '2', '0', 'Battle', 'Battle: Target your unbowed Personality with 3 or more Chi.  Either move him to another unresolved battlefield or destroy a Terrain at the current battlefield.', '3');
INSERT INTO acts VALUES ('Oath of Fealty', '2', '0', 'Limited', 'Limited: Permanently remove all Clan Alignments from all your Human Personalities without your Clan Alignment, permanently give them your Clan Alignment, and give them each a +1F/+1C token.', '3');

/* Insert into Region table */
INSERT INTO regions VALUES ('Beiden Shadows', '1', 'Singular', 'While Beiden Shadows is in play, units sent home from your Provinces may not move into battles for the rest of the turn.');
INSERT INTO regions VALUES ('City of Gold', '1', 'Singular', 'This Province has -1 Strength while this card is bowed.\nReaction: After you bow a Holding to produce Gold, bow this card: Produce 1 Gold for the same payment.');
INSERT INTO regions VALUES ('Fields of Pyrhic Victory', '1', 'Singular, Reaction', 'Infantry Followers and Infantry Personalities have -1F while at this Province.\nReaction: After a Limited or Open Action targets a Unique Personality you control, bow this card: Cancel it.');
INSERT INTO regions VALUES ('Plain of Fast Troubles', '1', 'Battle', 'Battle: If a face-up Personality in this Province, bring the Personality into play, waiving all costs and ignoring Honor requirements, as a defending unit in this battle. (You can do this even if there are no attacking units.)'); 
INSERT INTO regions VALUES ('Akui Cliffs' , '1', null, 'Each Personality with under 4 Chi has -2F while attacking or defending this Province.');
INSERT INTO regions VALUES ('Bridge to Jigoku', '1', 'Unique, Battle', 'Battle: Once per turn, each Personality in this battle has -2C (minimum 1) until after the Resolution Segment.');
INSERT INTO regions VALUES ('Campsite', '1', 'Reaction', 'Reaction: Once per turn, after a player assigns or moves a unit to attack this Province, draw a card.');
INSERT INTO regions VALUES ('Crossroads', '1', null, 'Lower the Gold cost of Holdings in this province by 3.');
INSERT INTO regions VALUES ('Farmlands', '1', 'Farm, Singular, Limited', 'Limited: Pay 2 Gold: Create a 1F Follower and attach it to your target Personality.');
INSERT INTO regions VALUES ('Fields of the Dead', '1', null, 'No player may assign any Personality with over 4 Force to battle at this Province.');
INSERT INTO regions VALUES ('Haunted Lands', '1', null, 'While in a battle at this Province, all Shadowlands Personalities and Followers have the ability, "Battle: Discard a card from your hand to produce a Fear X effect, where X is equal to the Focus Value of the discard.');
INSERT INTO regions VALUES ('Heimin Village', '1', null, 'Each Personality with over 3 Force has his or her Force lowered to 3 while attacking or defending this Province.');
INSERT INTO regions VALUES ('Mantis Isles', '1', null, 'Each Personality who is not a Mantis, Naval, Sailor, Sea, or Water card has -1F (minimum 0) while in a battle at this Province.');
INSERT INTO regions VALUES ('The Mountains Below Kyuden Hitomi', '1', 'Battle', 'Battle: Beginning with the top card of your Fate deck, draw and reveal each card until you reveal a terrain.  You may put this terrain immediately into play for this battle, or dicard it.  All other revealed cards are shuffled back into your deck.  You may do this once per battle.');
INSERT INTO regions VALUES ('Mountain Pass', '1', null, 'This Province gains +4 strength.  Provinces adjacent to this one have -1 strength.  (If a Province is destroyed, the one next to it becomes adjacent.)');
INSERT INTO regions VALUES ('River Delta', '1', 'Limited', 'Limited: Once per turn, pay 3 Gold.  Attach a 1F Naga Follower to one of your Naga Personalities.');
INSERT INTO regions VALUES ('Shi-Khan Wastes', '1', 'Shadowlands', 'Raise the Fear numbers printed on cards in this battle by 2.');
INSERT INTO regions VALUES ('Sunken City', '1', 'Underwater Region, Unique', 'While the Sunken City is in play, each of your Pearl Beds and Pearl Divers produces 1 extra Gold when bowed.');
INSERT INTO regions VALUES ('Swamplands', '1', null, 'Whenever you reveal a Fortification in this Province, replace it with a face-down Dynasty card.  Players cannot assign units to attack or defend this Province during the Cavalry Maneuvers Segment.');
INSERT INTO regions VALUES ('Fields of the Moon', '1', 'Singular, Reaction', 'Reaction: Once per turn, after you bring a Personality aligned with your Faction into play from one of your Provinces, pay 4 Gold to draw a Fate card.'); 

